version: "3.8"
services:
  agent-db:
    image: postgres:15-alpine
    container_name: agent_postgres
    restart: always
    environment:
      POSTGRES_USER: agent_user
      POSTGRES_PASSWORD: agent_password
      POSTGRES_DB: agent_db
    ports:
      - "5434:5432"
    volumes:
      - agent_db_data:/var/lib/postgresql/data

  

volumes:
  agent_db_data:
